/**
 * Every word the editor shows, in one file: the person reading it is a
 * Mongolian-speaking editor, and one place is where a translation gets reviewed.
 */
export const STRINGS = {
  placeholder: "Энд бичиж эхэлнэ үү…",
  slashHint: "Командын цэс нээхийн тулд / дарна уу.",
  toolbarLabel: "Бичвэрийн хэрэгсэл",
  headingLabel: "Бичвэрийн хэлбэр",
  headings: {
    0: "Энгийн текст",
    1: "Гарчиг",
    2: "Дэд гарчиг",
    3: "Жижиг гарчиг",
  },
  bold: "Тод",
  italic: "Налуу",
  underline: "Доогуур зураастай",
  strike: "Дундуур зураастай",
  link: "Холбоос",
  bullet: "Тэмдэгтэт жагсаалт",
  numbered: "Дугаарласан жагсаалт",
  quote: "Ишлэл",
  divider: "Тусгаарлах зураас",
  image: "Зураг",
  undo: "Буцаах",
  redo: "Дахин хийх",
  clear: "Формат арилгах",
  words: (count: number) => `${count} үг`,
  reading: (minutes: number) => `${minutes} мин уншина`,
  linkPopover: {
    title: "Холбоос",
    address: "Хаяг",
    placeholder: "shunkhlai.mn эсвэл https://…",
    newTab: "Шинэ цонхонд нээх",
    save: "Хадгалах",
    remove: "Холбоос устгах",
    cancel: "Болих",
    invalid: "Холбоосны хаяг буруу байна.",
  },
  imagePopover: {
    title: "Зураг оруулах",
    editTitle: "Зураг засах",
    address: "Зургийн хаяг",
    addressPlaceholder: "https://…",
    alt: "Зургийн тайлбар (дэлгэц уншигчид)",
    caption: "Зургийн доорх бичвэр",
    insert: "Оруулах",
    save: "Хадгалах",
    remove: "Зураг устгах",
    cancel: "Болих",
    invalid: "Хаяг https:// эсвэл / тэмдгээр эхэлсэн байх ёстой.",
  },
  slash: {
    menuLabel: "Командын цэс",
    empty: "Тохирох команд олдсонгүй",
    heading1: { label: "Гарчиг", hint: "Том гарчиг" },
    heading2: { label: "Дэд гарчиг", hint: "Дунд гарчиг" },
    heading3: { label: "Жижиг гарчиг", hint: "Жижиг гарчиг" },
    bullet: { label: "Тэмдэгтэт жагсаалт", hint: "Цэгтэй жагсаалт" },
    numbered: { label: "Дугаарласан жагсаалт", hint: "1, 2, 3 гэж дугаарлана" },
    quote: { label: "Ишлэл", hint: "Ишлэл эсвэл онцлох үг" },
    divider: { label: "Тусгаарлах зураас", hint: "Хэсгүүдийг ялгана" },
    image: { label: "Зураг", hint: "Хаягаар зураг оруулна" },
  },
  imageAtom: "Зураг",
  dividerAtom: "Тусгаарлах зураас",
} as const;
